### Machine Learning Pipeline

The dataset used for this example is obtained from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/dataset/222/bank+marketing).

The second part consists of creating a machine learning model to predict if the client will subscribe (yes/no) a term deposit (variable y).

#### Import Dataset

In [6]:
!python -m pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.8 MB 6.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.8 MB 8.0 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.8 MB 9.1 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.8 MB 8.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 9.1 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.3 MB 10.3 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 11.4 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.3 MB 11.5 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 12.1 MB/s eta 0:00:00
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.3 tzdata-2026.2

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
!python -m pip show pandas

Name: pandas
Version: 3.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by:

In [9]:
!python -m pip install joblib scikit-learn

Collecting joblib
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   --------------- ------------------------ 3.1/8.0 MB 16.8 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 14.2 MB/s eta 0:00:00
Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
# import libraries
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score

In [14]:
# read dataset
df = pd.read_csv(r"C:\Users\ASUS\Desktop\EADA\3º trimestre\ML Operations\Activities\mlops-and-system-design\session 2\bank-full_train_test.csv")

In [4]:
# read dataset
df = pd.read_csv("datasets/bank-full_train_test.csv")

NameError: name 'pd' is not defined

In [15]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,29,housemaid,married,primary,no,0,yes,no,cellular,15,jul,317,3,-1,0,unknown,no
1,57,management,divorced,secondary,no,396,no,no,cellular,12,aug,108,2,-1,0,unknown,no
2,54,blue-collar,married,primary,no,714,no,no,cellular,5,may,225,1,-1,0,unknown,no
3,52,services,married,secondary,no,2072,no,no,cellular,10,jul,224,1,-1,0,unknown,no
4,34,management,married,tertiary,no,1778,no,no,cellular,4,nov,358,1,162,2,failure,yes

#### Transform Dataset

In [16]:
# balance dataset
def balance_dataset(df: pd.DataFrame) -> pd.DataFrame:
    # Separate the classes
    df_y0 = df[df['y'] == 'no']
    df_y1 = df[df['y'] == 'yes']

    # Find the smaller class size
    min_size = len(df_y1)

    # Randomly sample from each class
    df_y0_balanced = df_y0.sample(n=min_size, random_state=42)

    # Concatenate back together
    df_balanced = pd.concat([df_y0_balanced, df_y1])

    # Shuffle the dataset
    df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

    return df_balanced

df = balance_dataset(df)

In [18]:
import pandas as pd

In [20]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,43,blue-collar,married,primary,no,50,no,no,unknown,28,may,90,8,-1,0,unknown,no
1,32,technician,single,secondary,no,40,no,no,cellular,8,aug,419,2,-1,0,unknown,yes
2,32,self-employed,single,tertiary,no,2559,no,no,cellular,7,jul,889,1,-1,0,unknown,yes
3,23,student,single,secondary,no,480,no,no,cellular,9,feb,742,2,182,1,failure,yes
4,32,management,single,tertiary,no,1169,yes,no,unknown,21,may,322,2,-1,0,unknown,no

In [23]:
# map target
df.loc[df["y"] == "yes", "y"] = "1"
df.loc[df["y"] == "no", "y"] = "0"
df["y"] = df["y"].astype(int)

In [24]:
# prepare dataset for classification model
class Transformer:
    def __init__(self):
        self.DROP_COLUMNS = []
        self.BINARY_FEATURES = [
            "housing",
            "loan",
            "default",
        ]

    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.drop(self.DROP_COLUMNS, axis=1)
        df = self._map_binary_column_to_int(df)
        df = self._map_month_to_int(df)

        return df

    def _map_binary_column_to_int(self, df: pd.DataFrame) -> pd.DataFrame:
        for col in self.BINARY_FEATURES:
            df[col] = df[col].map({"yes": 1, "no": 0})
        return df

    def _map_month_to_int(self, df: pd.DataFrame) -> pd.DataFrame:
        month_mapping = {
            "jan": 1,
            "feb": 2,
            "mar": 3,
            "apr": 4,
            "may": 5,
            "jun": 6,
            "jul": 7,
            "aug": 8,
            "sep": 9,
            "oct": 10,
            "nov": 11,
            "dec": 12,
        }
        df["month"] = df["month"].map(month_mapping)

        return df

In [25]:
# transform the dataset
df = Transformer().transform(df)

In [26]:
# encode categorical variables
ONE_HOT_ENCODE_COLUMNS = [
            "marital",
            "job",
            "education",
            "poutcome",
            "contact",
        ]

encoder = OneHotEncoder(drop='first', sparse_output=False).set_output(transform="pandas")
encoder.fit(df[ONE_HOT_ENCODE_COLUMNS])
encoded_df = encoder.transform(df[ONE_HOT_ENCODE_COLUMNS])
df = df.drop(columns=ONE_HOT_ENCODE_COLUMNS)
df = pd.concat([df, encoded_df], axis=1)

In [28]:
import os

# Crear la carpeta si no existe
os.makedirs("model_utils", exist_ok=True)

# Ahora guardar el encoder
joblib.dump(encoder, 'model_utils/encoder.pkl')

['model_utils/encoder.pkl']

In [29]:
# save encoder - future use
joblib.dump(encoder, 'model_utils/encoder.pkl')

['model_utils/encoder.pkl']

#### Train and evaluate model

In [30]:
# Split the data into training and test sets
X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [33]:
# Define the model hyperparameters
params = {
    "solver": "lbfgs",
    "max_iter": 1000,

    "random_state": 8888,
}

In [34]:
# Train the model
lr = LogisticRegression(**params)
lr.fit(X_train, y_train)

c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=8888)

In [35]:
# Predict on the test set
y_pred = lr.predict(X_test)

In [36]:
# Calculate metrics
f1_score = f1_score(y_test, y_pred)

### MLFlow Integration

In [38]:
!python -m pip install mlflow

Collecting mlflow
  Downloading mlflow-3.12.0-py3-none-any.whl.metadata (49 kB)
Collecting mlflow-skinny==3.12.0 (from mlflow)
  Downloading mlflow_skinny-3.12.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.12.0 (from mlflow)
  Downloading mlflow_tracing-3.12.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Collecting Flask<4 (from mlflow)
  Using cached flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4 (from mlflow)
  Downloading aiohttp-3.13.5-cp312-cp312-win_amd64.whl.metadata (8.4 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Using cached alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting cryptography<47,>=43.0.0 (from mlflow)
  Using cached cryptography-46.0.7-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Collecting matplotlib<4 (from mlflow)
  Using cached matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: numpy<3 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from mlflow) (2.4.4)
Collecting pandas<3 (from mlflow)
  Downloading pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting pyarrow<24,>=4.0.0 (from mlflow)
  Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: scikit-learn<2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from mlflow) (1.8.0)
Requirement already satisfied: scipy<2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from mlflow) (1.17.1)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Using cached sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.12.0->mlflow)
  Downloading cachetools-7.1.1-py3-none-any.whl.metadata (5.8 kB)
Collecting click<9,>=7.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting cloudpickle<4 (from mlflow-skinny==3.12.0->mlflow)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached databricks_sdk-0.108.0-py3-none-any.whl.metadata (43 kB)
Collecting fastapi<1 (from mlflow-skinny==3.12.0->mlflow)
  Using cached fastapi-0.136.1-py3-none-any.whl.metadata (28 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.12.0->mlflow)
  Using cached gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.12.0->mlflow)
  Downloading importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_api-1.41.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.12.0->mlflow)
  Downloading opentelemetry_proto-1.41.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_sdk-1.41.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: packaging<27 in c:\users\asus\appdata\roaming\python\python312\site-packages (from mlflow-skinny==3.12.0->mlflow) (26.2)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pydantic<3,>=2.0.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.12.0->mlflow)
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Collecting pyyaml<7,>=5.1 (from mlflow-skinny==3.12.0->mlflow)
  Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Collecting requests<3,>=2.17.3 (from mlflow-skinny==3.12.0->mlflow)
  Using cached requests-2.34.1-py3-none-any.whl.metadata (4.8 kB)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting starlette<1 (from mlflow-skinny==3.12.0->mlflow)
  Downloading starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Collecting typing-extensions<5,>=4.0.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uvicorn<1 (from mlflow-skinny==3.12.0->mlflow)
  Using cached uvicorn-0.46.0-py3-none-any.whl.metadata (6.7 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4->mlflow)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4->mlflow)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4->mlflow)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4->mlflow)
  Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4->mlflow)
  Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4->mlflow)
  Downloading propcache-0.5.2-cp312-cp312-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4->mlflow)
  Downloading yarl-1.23.0-cp312-cp312-win_amd64.whl.metadata (82 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Using cached mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Collecting cffi>=2.0.0 (from cryptography<47,>=43.0.0->mlflow)
  Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)
  Using cached pywin32-311-cp312-cp312-win_amd64.whl.metadata (10 kB)
Collecting urllib3>=1.26.0 (from docker<8,>=4.0.0->mlflow)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting blinker>=1.9.0 (from Flask<4->mlflow)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from Flask<4->mlflow)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from Flask<4->mlflow)
  Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow)
  Using cached werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Collecting contourpy>=1.0.1 (from matplotlib<4->mlflow)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib<4->mlflow)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib<4->mlflow)
  Using cached fonttools-4.63.0-cp312-cp312-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib<4->mlflow)
  Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Collecting pillow>=8 (from matplotlib<4->mlflow)
  Using cached pillow-12.2.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib<4->mlflow)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting pytz>=2020.1 (from pandas<3->mlflow)
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Using cached greenlet-3.5.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python312\site-packages (from click<9,>=7.0->mlflow-skinny==3.12.0->mlflow) (0.4.6)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow)
  Using cached google_auth-2.52.0-py3-none-any.whl.metadata (5.5 kB)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting typing-inspection>=0.4.2 (from fastapi<1->mlflow-skinny==3.12.0->mlflow)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.12.0->mlflow)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.12.0->mlflow)
  Using cached zipp-3.23.1-py3-none-any.whl.metadata (3.6 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting opentelemetry-semantic-conventions==0.62b1 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_semantic_conventions-0.62b1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: wcwidth in c:\users\asus\appdata\roaming\python\python312\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.7.0)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow)
  Using cached pydantic_core-2.46.4-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow)
  Using cached charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow)
  Using cached idna-3.15-py3-none-any.whl.metadata (7.7 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow)
  Using cached certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting anyio<5,>=3.6.2 (from starlette<1->mlflow-skinny==3.12.0->mlflow)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting h11>=0.8 (from uvicorn<1->mlflow-skinny==3.12.0->mlflow)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow)
  Using cached smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow)
  Using cached pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Downloading mlflow-3.12.0-py3-none-any.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.6 MB 3.7 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/10.6 MB 5.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/10.6 MB 5.9 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 6.0/10.6 MB 5.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.6/10.6 MB 6.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.6 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 6.6 MB/s eta 0:00:00
Downloading mlflow_skinny-3.12.0-py3-none-any.whl (3.3 MB)
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
   ------------------------- -------------- 2.1/3.3 MB 9.8 MB/s eta 0:00:01
   ---------------------------------------- 3.3/3.3 MB 8.7 MB/s eta 0:00:00
Downloading mlflow_tracing-3.12.0-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 9.6 MB/s eta 0:00:00
Downloading aiohttp-3.13.5-cp312-cp312-win_amd64.whl (460 kB)
Using cached alembic-1.18.4-py3-none-any.whl (263 kB)
Using cached cryptography-46.0.7-cp311-abi3-win_amd64.whl (3.5 MB)
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached flask-3.1.3-py3-none-any.whl (103 kB)
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
Using cached matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
Downloading pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.0 MB 16.7 MB/s eta 0:00:01
   ---------- ----------------------------- 2.9/11.0 MB 7.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/11.0 MB 7.5 MB/s eta 0:00:01
   --------------------------- ------------ 7.6/11.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 9.7 MB/s eta 0:00:00
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   --- ------------------------------------ 2.4/27.6 MB 11.2 MB/s eta 0:00:03
   ------- -------------------------------- 5.2/27.6 MB 12.2 MB/s eta 0:00:02
   ------------ --------------------------- 8.4/27.6 MB 13.0 MB/s eta 0:00:02
   ---------------- ----------------------- 11.3/27.6 MB 12.8 MB/s eta 0:00:02
   ------------------- -------------------- 13.6/27.6 MB 12.6 MB/s eta 0:00:02
   ----------------------- ---------------- 16.3/27.6 MB 12.5 MB/s eta 0:00:01
   --------------------------- ------------ 19.1/27.6 MB 12.6 MB/s eta 0:00:01
   -------------------------------- ------- 22.3/27.6 MB 12.8 MB/s eta 0:00:01
   ------------------------------------ --- 25.2/27.6 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.6 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 12.2 MB/s eta 0:00:00
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
Using cached sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl (2.1 MB)
Using cached waitress-3.0.2-py3-none-any.whl (56 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-7.1.1-py3-none-any.whl (16 kB)
Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl (183 kB)
Using cached click-8.3.3-py3-none-any.whl (110 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached databricks_sdk-0.108.0-py3-none-any.whl (887 kB)
Using cached fastapi-0.136.1-py3-none-any.whl (117 kB)
Using cached fonttools-4.63.0-cp312-cp312-win_amd64.whl (2.3 MB)
Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Using cached gitpython-3.1.50-py3-none-any.whl (212 kB)
Using cached graphql_core-3.2.8-py3-none-any.whl (207 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached greenlet-3.5.0-cp312-cp312-win_amd64.whl (238 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl (46 kB)
Using cached opentelemetry_api-1.41.1-py3-none-any.whl (69 kB)
Using cached importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Downloading opentelemetry_proto-1.41.1-py3-none-any.whl (72 kB)
Using cached opentelemetry_sdk-1.41.1-py3-none-any.whl (180 kB)
Using cached opentelemetry_semantic_conventions-0.62b1-py3-none-any.whl (231 kB)
Using cached pillow-12.2.0-cp312-cp312-win_amd64.whl (7.1 MB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading propcache-0.5.2-cp312-cp312-win_amd64.whl (42 kB)
Using cached protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-win_amd64.whl (2.1 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached pywin32-311-cp312-cp312-win_amd64.whl (9.5 MB)
Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Using cached requests-2.34.1-py3-none-any.whl (73 kB)
Using cached sqlparse-0.5.5-py3-none-any.whl (46 kB)
Downloading starlette-0.52.1-py3-none-any.whl (74 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached uvicorn-0.46.0-py3-none-any.whl (70 kB)
Using cached werkzeug-3.1.8-py3-none-any.whl (226 kB)
Downloading yarl-1.23.0-cp312-cp312-win_amd64.whl (87 kB)
Using cached mako-1.3.12-py3-none-any.whl (78 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached certifi-2026.4.22-py3-none-any.whl (135 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl (159 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached google_auth-2.52.0-py3-none-any.whl (245 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.15-py3-none-any.whl (72 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached zipp-3.23.1-py3-none-any.whl (10 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Using cached smmap-5.0.3-py3-none-any.whl (24 kB)
Using cached pyasn1-0.6.3-py3-none-any.whl (83 kB)

  WARNING: The scripts pywin32_postinstall.exe and pywin32_testall.exe are installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script huey_consumer.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script waitress-serve.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sqlformat.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dotenv.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script uvicorn.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\~andas'.
  You can safely remove it manually.
  WARNING: The script mako-render.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flask.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script alembic.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script fastapi.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mlflow.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mlflow.exe is installed in 'c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
# import libraries
import mlflow
from mlflow.models import infer_signature

In a new terminal, run a local Tracking Server with the following command:

`mlflow server --host 127.0.0.1 --port 8080`

In [40]:
# Set our tracking server uri for logging
mlflow.set_tracking_uri(uri="http://127.0.0.1:8080")

In [41]:
# Create a new MLflow Experiment
mlflow.set_experiment("LR Experiment")

# Start an MLflow run
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)

    # Log the loss metric
    mlflow.log_metric("f1_score", f1_score)

    # Set a tag that we can use to remind ourselves what this run was for
    mlflow.set_tag("Training Info", "Basic LR model to present MLFlow capabilities")

    # Infer the model signature
    signature = infer_signature(X_train, lr.predict(X_train))

    # Log the model
    model_info = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="bank_model",
        signature=signature,
        input_example=X_train,
        registered_model_name="bank-model-basic",
    )

2026/05/14 19:35:41 INFO mlflow.tracking.fluent: Experiment with name 'LR Experiment' does not exist. Creating a new experiment.
c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/05/14 19:35:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run adaptable-chimp-212 at: http://127.0.0.1:8080/#/experiments/564433805273450941/runs/6961ed15237247159cf1dc309bd42aed
🧪 View experiment at: http://127.0.0.1:8080/#/experiments/564433805273450941

MlflowException: API request to endpoint /api/2.0/mlflow/logged-models failed with error code 404 != 200. Response body: '<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
'